app = 'ollama-honeypot'
primary_region = 'sjc'

[build]

[[services]]
  protocol = "tcp"
  internal_port = 11434

  [[services.ports]]
    port = 11434
    handlers = ["proxy_proto"]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
